#!/usr/bin/env python3

import argparse
import ast
import configparser
import sys
from pathlib import Path
from string import Template


def build_readme(paths):
    config = configparser.ConfigParser()
    with open("setup.cfg") as f:
        config.read_file(f)
    with open("README_template.md") as f:
        template = Template(f.read())
    data = ""
    for path in paths:
        with open(path, "r") as f:
            module = ast.parse(f.read())
        for node in module.body:
            if isinstance(node, ast.FunctionDef) and node.name == "main":
                doc = ast.get_docstring(node)
                if doc:
                    doc = doc[0].lower() + doc[1:-1]
                    name = Path(path).stem.replace("_", "-")
                    data += f"* `{name}`: {doc}\n"
    sys.stdout.write(
        template.substitute(
            description=data,
            name=config.get("metadata", "name"),
            version=config.get("metadata", "version"),
        )
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("files", metavar="file", nargs="*")
    args = parser.parse_args()

    build_readme(args.files)


if __name__ == "__main__":
    main()
