#!/usr/bin/env python3

import argparse
import ast
import os
import sys
from string import Template


def script_name(path):
    name = os.path.basename(path).replace("_", "-")
    return os.path.splitext(name)[0]


def build_readme(paths):
    with open("README_template.md") as f:
        template = Template(f.read())
    data = ""
    for path in paths:
        with open(path, "r") as f:
            module = ast.parse(f.read())
        for node in module.body:
            if isinstance(node, ast.FunctionDef) and node.name == "main":
                doc = ast.get_docstring(node)
                if doc:
                    doc = doc[0].lower() + doc[1:-1]
                    data += "* `{name}`: {desc}\n".format(
                        name=script_name(path), desc=doc
                    )
    sys.stdout.write(template.substitute(description=data))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("files", metavar="file", nargs="*")
    args = parser.parse_args()

    build_readme(args.files)


if __name__ == "__main__":
    main()
